=== TrueIddys/ProjetJ/src/xml/dr.dtd
<!ELEMENT dr (fonctions,p+)>

<!ELEMENT fonctions (f+)>

<!ELEMENT f EMPTY>
<!ATTLIST f id ID #REQUIRED>

<!ELEMENT p ((c+)|((m|pd|pg)+))>

<!ELEMENT c (pg*,m+,pd*)>
<!ATTLIST c id ID #REQUIRED
            c IDREF #REQUIRED>

<!ELEMENT m (#PCDATA)>
<!ELEMENT pg (#PCDATA)>
<!ELEMENT pd (#PCDATA)>

=== TrueIddys/ProjetJ/src/xml/exemple2_pour_edition.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dr SYSTEM "dr.dtd">
<dr>
<fonctions><f id="s"/><f id="v"/><f id="i"/><f id="_s"/><f id="_v"/></fonctions>
<p><m>Aux</m> <m>délégations</m><pd>,</pd> <m>M.</m> <m>Jonnart</m> <m>a</m> <m>nié</m> <m>que</m> <m>le</m> <m>projet</m> <m>d’</m><m>impôt</m> <m>nouveau</m> <m>fût</m> <m>un</m> <m>artifice</m> <m>pour</m> <m>boucler</m> <m>le</m> <m>budget</m><pd>.</pd></p>
<p><m>Une</m> <m>dizaine</m> <m>de</m> <m>camelots</m> <m>qui</m> <m>criaient</m> <m>le</m> <m>récit</m> <m>d’</m><m>un</m> <m>chimérique</m> <m>attentat</m> <m>anarchiste</m> <m>à</m> <m>la</m> <m>Madeleine</m> <m>ont</m> <m>été</m> <m>arrêtés</m><pd>.</pd></p>
<p><m>Une</m> <m>criminelle</m> <m>mégère</m><pd>,</pd> <m>Mme</m> <m>Tulle</m><pd>,</pd> <m>a</m> <m>eu</m><pd>,</pd> <m>des</m> <m>assises</m> <m>de</m> <m>Rouen</m><pd>,</pd> <m>dix</m> <m>ans</m> <m>de</m> <m>travaux</m> <m>forcés</m><pd>,</pd> <m>et</m> <m>son</m> <m>amant</m> <m>cinq</m> <m>ans</m><pd>.</pd></p>
<p><m>Bernard</m><pd>,</pd> <m>à</m> <m>Essoyes</m> <pg>(</pg><m>Aube</m><pd>)</pd><pd>,</pd> <m>25</m> <m>ans</m><pd>,</pd> <m>a</m> <m>assommé</m> <m>M.</m> <m>Dufert</m><pd>,</pd> <m>qui</m> <m>en</m> <m>a</m> <m>89</m><pd>,</pd> <m>et</m> <m>poignardé</m> <m>sa</m> <m>femme</m><pd>.</pd></p>
</dr>

=== TrueIddys/ProjetJ/src/xml/exemple1_pour_edition.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dr SYSTEM "dr.dtd">
<dr>
<fonctions><f id="s"/><f id="v"/><f id="i"/><f id="_s"/><f id="_v"/></fonctions>
<p><m>Dans</m> <m>un</m> <m>assaut</m><pd>,</pd> <m>le</m> <m>maître</m> <m>d’</m><m>armes</m> <m>Pictori</m> <m>a</m> <m>été</m> <m>blessé</m><pd>,</pd> <m>mortellement</m> <m>peut-être</m><pd>,</pd> <m>par</m> <m>un</m> <m>amateur</m><pd>,</pd> <m>M.</m> <m>Breugnot</m><pd>.</pd></p>
<p><m>Le</m> <m>sombre</m> <m>rôdeur</m> <m>aperçu</m> <m>par</m> <m>le</m> <m>mécanicien</m> <m>Gicquel</m> <m>près</m> <m>de</m> <m>la</m> <m>gare</m> <m>d’</m><m>Herblay</m><pd>,</pd> <m>est</m> <m>retrouvé</m> <pd>:</pd> <m>Jules</m> <m>Ménard</m><pd>,</pd> <m>ramasseur</m> <m>d’</m><m>escargots</m><pd>.</pd></p>
<p><m>Le</m> <m>conseil</m> <m>municipal</m> <m>de</m> <m>Toulon</m> <m>voulait</m> <m>pour</m> <m>la</m> <m>police</m> <m>la</m> <m>journée</m> <m>de</m> <m>huit</m> <m>heures</m><pd>.</pd> <m>Sa</m> <m>délibération</m> <m>est</m> <m>annulée</m> <m>par</m> <m>le</m> <m>préfet</m><pd>.</pd></p>
<p><m>Le</m> <m>ministre</m> <m>des</m> <m>Finances</m> <m>a</m> <m>prescrit</m> <m>aux</m> <m>percepteurs</m> <m>toulonnais</m> <m>d’</m><m>être</m> <m>bénins</m> <m>aux</m> <m>contribuables</m> <m>lésés</m> <m>par</m> <m>les</m> <m>grèves</m><pd>.</pd></p>
</dr>

=== TrueIddys/ProjetJ/src/xml/exemple3_pour_edition.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dr SYSTEM "dr.dtd">
<dr>
<fonctions><f id="s"/><f id="v"/><f id="i"/><f id="_s"/><f id="_v"/></fonctions>
<p><m>En</m> <m>désaccord</m> <m>politique</m><pd>,</pd> <m>MM.</m> <m>Bégouen</m><pd>,</pd> <m>publiciste</m><pd>,</pd> <m>et</m> <m>Bepmale</m><pd>,</pd> <m>député</m><pd>,</pd> <m>s'</m><m>étaient</m> <m>donné</m> <m>du</m> <pg>«</pg> <m>voleur</m> <pd>»</pd> <m>et</m> <m>du</m> <pg>«</pg> <m>lâche</m> <pd>»</pd><pd>.</pd> <m>Réconciliés</m><pd>.</pd></p>
<p><m>Pour</m> <m>son</m> <m>affiche</m> <m>contre</m> <m>les</m> <m>Jaunes</m><pd>,</pd> <m>les</m> <m>externes</m> <m>du</m> <m>lycée</m> <m>de</m> <m>Brest</m> <m>ont</m> <m>conspué</m> <m>leur</m> <m>professeur</m><pd>,</pd> <m>M.</m> <m>Litalien</m><pd>,</pd> <m>adjoint</m> <m>au</m> <m>maire</m><pd>.</pd></p>
<p><m>L'</m><m>infirmière</m> <m>Élise</m> <m>Bachmann</m><pd>,</pd> <m>dont</m> <m>c'</m><m>était</m> <m>hier</m> <m>le</m> <m>jour</m> <m>de</m> <m>sortie</m><pd>,</pd> <m>s'</m><m>est</m> <m>manifestée</m> <m>folle</m> <m>dans</m> <m>la</m> <m>rue</m><pd>.</pd></p>
<p><m>Plainte</m> <m>a</m> <m>été</m> <m>portée</m> <m>par</m> <m>le</m> <m>médecin</m> <m>persan</m> <m>Djaï</m> <m>Khan</m> <m>contre</m> <m>un</m> <m>sien</m> <m>compatriote</m> <m>qui</m> <m>lui</m> <m>vola</m> <m>une</m> <m>tiare</m><pd>.</pd></p>
<p><m>Certaine</m> <m>folle</m> <m>arrêtée</m> <m>dans</m> <m>la</m> <m>rue</m> <m>s'</m><m>était</m> <m>abusivement</m> <m>donnée</m> <m>pour</m> <m>l'</m><m>infirmière</m> <m>Élise</m> <m>Bachmann</m><pd>.</pd> <m>Celle-ci</m> <m>est</m> <m>en</m> <m>parfaite</m> <m>santé</m><pd>.</pd></p>
<p><m>Place</m> <m>du</m> <m>Panthéon</m><pd>,</pd> <m>des</m> <m>électeurs</m> <m>échauffés</m> <m>tentèrent</m> <m>de</m> <m>rôtir</m> <m>un</m> <m>mannequin</m> <m>figurant</m> <m>M.</m> <m>Auffray</m><pd>,</pd> <m>candidat</m> <m>battu</m><pd>.</pd> <m>On</m> <m>les</m> <m>dispersa</m><pd>.</pd></p>
</dr>
